[package]
name = "html-tools"
version = "0.1.0"
authors = ["skuhinek@gmail.com <skuhinek@gmail.com>"]

[dependencies]
regex = "0.1.75"
clipboard-win = "1.8.0"

[dependencies.user]
path = "../user"

[profile.release]
lto = true
